// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANTlf1d4fXG-4mtapejF7GqB2wp30oGiQ',
    appId: '1:396063305758:web:21f82cf79c4a5bf04cbe0f',
    messagingSenderId: '396063305758',
    projectId: 'fir-flutter-repairbike',
    authDomain: 'fir-flutter-repairbike.firebaseapp.com',
    storageBucket: 'fir-flutter-repairbike.appspot.com',
    measurementId: 'G-KH48Q8ZDM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZblQj4wVfgHiz2hli-GQ_Y45B412D0dU',
    appId: '1:396063305758:android:617fb549db4c5dad4cbe0f',
    messagingSenderId: '396063305758',
    projectId: 'fir-flutter-repairbike',
    storageBucket: 'fir-flutter-repairbike.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGVOLd5LaJg-3OLvVh6SsGIgdL4zFFkxw',
    appId: '1:396063305758:ios:635fa8c8556481ef4cbe0f',
    messagingSenderId: '396063305758',
    projectId: 'fir-flutter-repairbike',
    storageBucket: 'fir-flutter-repairbike.appspot.com',
    iosClientId: '396063305758-r4sklrs033571mqd1nkj7odhbmfm09ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
